defaults:
  - data: pubmedqa
  - model/student: llama3_1b_lora
  - model/teacher: llama3_1b
  - train: base
  - rag: chroma
  - _self_

deepspeed:
  teacher: ${hydra:runtime.cwd}/.conf/deepspeed/teacher.json
  student: ${hydra:runtime.cwd}/.conf/deepspeed/student.json

use_ddp: True
verbose: True
num_pairs: 1
seed: 42