hf_model:
  _target_: "transformers.AutoModelForCausalLM.from_pretrained"
  pretrained_model_name_or_path: "meta-llama/Llama-3.2-1B-Instruct"  
  device_map: "auto" 
  # attn_implementation: "xformers"
  dtype: "bfloat16"

gradient_checkpointing: true

peft:
  _target_: "peft.LoraConfig"
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  # target_modules: ["q_proj","k_proj","v_proj","up_proj","down_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"

embedder:
  _target_: "sentence_transformers.SentenceTransformer"
  name: "sentence-transformers/all-MiniLM-L6-v2"  # frozen for contrastive loss
